image: r-base:3.5.2

variables:
  R_LIBS_USER: $CI_PROJECT_DIR/.rcache/

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - $R_LIBS_USER

stages:
  - render

before_script:
  - apt-get update -qq && apt-get -y -qq install make zip gawk
  - test ! -d $R_LIBS_USER && mkdir $R_LIBS_USER
  - R -e "show(paste('Using libPaths', .libPaths()))"
  - R -e "install.packages(c('randtests', 'ggplot2', 'lubridate'))"

make:
  stage: render
  script:
    - make random.html
  artifacts:
    paths:
      - $CI_PROJECT_DIR/*.html

